const keywordsArray = [
  "awwwards",
  `animanoir`,
  `blog`,
  `Óscar A. Montiel`,
  `animación`,
  `animation`,
  "interactive",
  "creative",
  "developer",
  "3d",
  "2d",
  "idm",
  "unity",
  "three js",
  "aphex twin",
  "art",
  "ghosts",
  "fantasmas",
  "arte digital",
  "digital art",
  "interacción",
  "frontend",
  "react",
  "html 5",
  "web developer",
  "creative agencies",
  "web developer portafolio",
  "website developer",
  "creative studio",
  "web design",
  "graphic designers",
  "interactive design",
  "freelance web developer",
  "desarrollo web",
  "diseño interactivo",
  "web interactiva",
  "programador",
  "animador",
  "webflow",
  "gsnap",
  "cyberpunk",
  "futurism",
]

export { keywordsArray }
